### ISSUE TITLE
Titlul la articol rmq

### ISSUE THREAD

**Issue by TraianDanciu** [roalgo-discord/arhiva-educationala#43]
Titlul la articolul de rmq ar trebui sa fie `Sparse Table. Binary Lifting. Range Minimum Query`, pentru ca eu fac articolul si scopul principal este sa explic sparse table si binary lifting. Dupa aceea vine si rmq si de aia am vrut sa fie mentionate toate numele astea.

**Comment by susanthenerd** [comment]
Titlu se poate edita in `mkdocs.yml`
